include android-toolchain.mak

TARGET_LIST = x86_64-softmmu

ifeq ($(TARGET_ARCH), arm)
    QEMU_TARGET_CPU = armv4b
else
    QEMU_TARGET_CPU = i686
endif

config:
	echo TOOLCHAIN DIR: $(TOOLCHAIN_DIR)
	echo NDK ROOT: $(NDK_ROOT) 
	echo NDK PLATFORM: $(NDK_PLATFORM) 
	echo USR INCLUDE: $(NDK_INCLUDE)

	cd ./qemu	; \
	./configure 	--disable-kvm --disable-curses --target-list=$(TARGET_LIST) \
			--disable-vhost-net --disable-spice --disable-smartcard-nss --disable-uuid \
			--disable-vnc-jpeg  --disable-vnc-png --enable-vnc-thread --disable-attr \
			--disable-linux-aio --disable-pie --disable-smartcard --disable-smartcard-nss \
			--disable-nptl --disable-opengl --disable-zlib-test --with-coroutine=gthread \
			--audio-card-list= --audio-drv-list= \
			--disable-guest-agent --android --less-warnings --cpu=$(QEMU_TARGET_CPU) \
			--cross-prefix=$(TOOLCHAIN_PREFIX) \
			--extra-cflags=" -I$(NDK_ROOT)/$(NDK_PLATFORM)/$(USR_INCLUDE) -I../limbo/include -I../glib/glib -I../glib -I../glib/gmodule -I../glib/io -I../limbo/include -I../../glib/glib -I../../glib -I../../glib/gmodule -I../../glib/io -I../SDL/include"

