//Override SDL config
#undef SDL_VIDEO_OPENGL_ES
#define SDL_VIDEO_OPENGL_ES	1
#undef SDL_VIDEO_RENDER_OGL_ES
#define SDL_VIDEO_RENDER_OGL_ES	1
#undef SDL_VIDEO_RENDER_OGL_ES2
#define SDL_VIDEO_RENDER_OGL_ES2	0
