# Automatically generated by configure - do not modify
SRC_PATH=/media/DATA/prj/opensource/limbo-android/jni/qemu/roms/seabios
CC=/home/dev/tools/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/arm-linux-androideabi-gcc
BCC=bcc
CPP=/home/dev/tools/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/arm-linux-androideabi-cpp
OBJCOPY=objcopy
IASL=iasl
LD=/home/dev/tools/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/arm-linux-androideabi-ld
